### ISSUE TITLE
when writing tests, if i have declared CallParameters in params of test fn

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/marine#101]
please inject something meaningful - this boilerplate will stimulate writing secured code

**Comment by folex** [comment]
the problem and the context are not clear. Can you please provide meaningful issue name, code example, what you have tried to do, what you expected and what you got?

**Comment by dzmitry-lahoda** [comment]
#[marine_test]
fn test(cp: CallParameters, sevice: MyServiceImpl) {
   let call = service.init(cp);
  let other = CallParameters { other peer , ..cp};
  service.init(cp)// fail
 
}

**Comment by folex** [comment]
@dzmitry-lahoda what did you expect to happen?

**Comment by dzmitry-lahoda** [comment]
i have to write huge boilerplates in many areas this is one of this. it is pain to write anything because too much ceremony and  unkowns.

**Comment by folex** [comment]
what causes boilerplate and the ceremony?

**Comment by dzmitry-lahoda** [comment]
most of methods must be secure. i will write marine init with cp manually each time.

**Comment by dzmitry-lahoda** [comment]
in this case.

**Comment by dzmitry-lahoda** [comment]
Could Inject call parameters into any secure method either.
```
#[marine]
fn admin_stuff(cp: Callparameters)
```

so that default test method would also have these if `marine` fn had this.

**Comment by mikevoronov** [comment]
`marine_test` has evolved a lot since the time this issus was created. DX also was dramatically improved, so I'll close this issue, but if you feel that there is still a room for improvement, please file an issue in the [marine-rs-sdk-test](https://github.com/fluencelabs/marine-rs-sdk-test) repo.
