### ISSUE TITLE
allow usage of aliases

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/marine#107]
```rust
pub type PeerId = String;
/// meta service description (longer lived than service id, not same as blueprint id - may span over several blueprints and services), owned same security body and in same replica set
#[marine]
pub struct ReplicaSetServiceInfo {
    /// replica set id
    pub id: PeerId,
    /// nominal type, like `example.org/foobar`, 
    pub type_: String, 
}
```

```
error[E0599]: no method named `__m_generated_serialize` found for struct `String` in the current scope
   |
31 | #[marine]
   | ^^^^^^^^^ method not found in `String`
   |
   = note: this error originates in the attribute macro `marine` (in Nightly builds, run with -Z macro-backtrace for more info)
```

as it seems marine detects string alias, but for some reason does not want to handle that

**Comment by mikevoronov** [comment]
Basically, it's impossible to do without user help in procedure macros. This crux of the problem is that a proc macro receives just raw token streams without any types. So, macro could only obtain literal `"PeerId"` for your type and that's all. At the moment, `marine` macro handles it in simple way and treat all such non-Rust (I mean not `String`, `Vec` and primitive types) types as structs and expects that these structs are wrapped with `#[marine]` also. In its turn such wrapping generates some glue code (in this example `__m_generated_serialize`) that macro expects to be implemented for such type. That why you see such a error, and we don't have a chance to improve this error message somehow without `build.rs`, because macro don't have info about code outside its scope.

I know two possible ways to solve this problem:
1. Add attributes to `#[marine]` that will give macro info that this `PeerId` is a `String`, f.e. `#[marine(PeerId = String)]`
2. Use `build.rs`, that will require a lot of work

**Comment by mikevoronov** [comment]
FYI: `#[marine]` and `#[marine_test]` macros defined in the [marine-rs-sdk](https://github.com/fluencelabs/marine-rs-sdk) repo. So, it'd be better to file all such issues (such as https://github.com/fluencelabs/marine/issues/98  https://github.com/fluencelabs/marine/issues/101 https://github.com/fluencelabs/marine/issues/102) there.

**Comment by mikevoronov** [comment]
> 'method not found in String`, at least some minor imrpove could be done to report that PeerId type in not supported or else. For now it tells that it is string.

The macro generates glue code in the following way:
1. for each struct wrapped with `#[marine]` there would be generated `impl` block with two methods for se/de. You could find an example in our generation [tests](https://github.com/fluencelabs/marine-rs-sdk/blob/master/crates/marine-macro-impl/tests/generation_tests/records/call_parameters/expanded.rs#L19).
2. for each field in a struct there would be a [comparison](https://github.com/fluencelabs/marine-rs-sdk/blob/master/crates/marine-macro-impl/src/parsed_type.rs#L80) with some literals ('i32', 'Vec', ...) that represents known for sdk types. If it matches, all is good and type is known. If not, the macro considers that it's a struct that is wrapped with `#[marine]`.
3. from 1 and 2 it follows that the macro expects some special methods to be generated for each "unknown" types, and it would use them for generated se/de ((example)[https://github.com/fluencelabs/marine-rs-sdk/blob/master/crates/marine-macro-impl/tests/generation_tests/records/call_parameters/expanded.rs#L44]). And in macro it's impossible to check whether this methods generated or not. It could be considered as a form of duck typing. And we could improve this error message only with `build.rs` that could analyze an entire project not just scoped wrapped with a macro.

**Comment by dzmitry-lahoda** [comment]
not exactly same, but relevant https://github.com/fluencelabs/marine/issues/115

**Comment by dzmitry-lahoda** [comment]
why there is no serde for string? I mean why there are well known types and they are not just use serde as other types? Type is not know - call serde, type is known - call serde?

**Comment by mikevoronov** [comment]
> i know that #[] macro invocations can talk to each other, without build rs. i have seen such on crates on cargo. without build rs.

Wow, could you please provide the link?

**Comment by mikevoronov** [comment]
> why there is no serde for string? I mean why there are well known types and they are not just use serde as other types? Type is not know - call serde, type is known - call serde?

But how would you de it back without knowledge of initial type? It's possible to do on other modules that have the same definition of type, but
- this'll make impossible a proper type checking
- we can't de types inside marine runtime, f.e. [here](https://github.com/fluencelabs/marine/blob/master/fluence-app-service/src/service.rs#L79)
- also we want to support other langs, f.e. SQlite is written on C
- se with serde requires additional allocation and copying

**Comment by dzmitry-lahoda** [comment]
> also we want to support other langs, f.e. SQlite is written on C

i see, but i do not care about be able to call rust wasm from c wasm.

> se with serde requires additional allocation and copying

if i have `type X = string`, would not serde_json::to_vec::<X>()` just provide string? so in case of unknown type it will call serder,alloce, but still be usual string? 

> this'll make impossible a proper type checking

type checking in marine runtime? 

from my side, could write workaround like 
```
enum X(string)
```

but that neither supported, not i want to deal with dots in aqua

**Comment by mikevoronov** [comment]
I close this issue in favor of https://github.com/fluencelabs/marine-rs-sdk/issues/73.
