### ISSUE TITLE
add service interface into test for ease of typing

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/marine#98]
now
```rust
#[marine_test]
fn math() {
   service.add(1,2) 
}
```  

add is not suggested in IDE, but if
```rust
#[marine_test]
fn math(service: MathProxy) {
   service.add(1,2) 
}
```  

than Rust IDE will help me

**Comment by mikevoronov** [comment]
Which Rust IDE do you mean? Because Idea wouldn't suggest anything for types generated with proc macro not depending of their place.

**Comment by dzmitry-lahoda** [comment]
never mind,

**Comment by mikevoronov** [comment]
@dzmitry-lahoda it still could make sense, because having an argument in a function looks more understandable. I want leave this issue closed and opened issue in the marine-rs-sdk repo https://github.com/fluencelabs/marine-rs-sdk/issues/43 that fits more for it.
